name: Artemis

on:
  pull_request:
  push:
    branches:
      - main
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # STD_DEV is fake but it's needed by action-benchmarks
      - name: Compute Global benchmark
        run: |
            TOTAL_RUN=$(cat benchmark.json| jq '[.. | objects | .mean] | add' )
            OPS=$(echo "$((1 / $TOTAL_RUN))")
            STD_DEV=$(echo "$((0.1 * $TOTAL_RUN))") 
            cat benchmark.json | jq '.benchmarks |= [{"group": "IdfM", "name": "global_test", "fullname": "artemis/global_test", "params": null, "param": null, "extra_info": {}, "stats": { "ops" : "'"$OPS"'", "mean" : "'"$TOTAL_RUN"'", "rounds" : 1, "stddev" : "'"$STD_DEV"'" }  }] + .' >> benchmark_edit.json
      - name: Store benchmark result
        uses: AzHicham/github-action-benchmark@v2
        with:
          tool: 'pytest'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: 'gh-pages'
          benchmark-data-dir-path: '.'
          output-file-path: benchmark_edit.json
          fail-on-alert: true
          alert-threshold: '150%'
          comment-on-alert: true
          commit-id: ${{ github.event.client_payload.commit_id }}
          commit-message: ${{ github.event.client_payload.commit_message }}
          commit-timestamp: ${{ github.event.client_payload.commit_timestamp }}
          commit-url: ${{ github.event.client_payload.commit_url }}/commit/${{ github.event.client_payload.commit_id }}
          commit-name: ${{ github.event.client_payload.commit_username }}
